import { defineSchema } from "convex/server";
import { defineTable } from "convex/server";
import { v } from "convex/values";

export const fileTypes = v.union(
  v.literal("image"), 
  v.literal('csv'), 
  v.literal('pdf'), 
  v.literal('doc'), 
  v.literal('docx'), 
  v.literal('xls'), 
  v.literal('xlsx'), 
  v.literal('ppt'), 
  v.literal('pptx'), 
  v.literal('txt'), 
  v.literal('zip'), 
  v.literal('rar'),
  v.literal('mp4'), 
  v.literal('mov'), 
  v.literal('avi'), 
  v.literal('mkv'), 
  v.literal('flv'), 
  v.literal('wmv'),
  v.literal('mp3'), 
  v.literal('wav'), 
  v.literal('flac'), 
  v.literal('aac'), 
  v.literal('ogg'),
  v.literal('jpeg'), 
  v.literal('png'), 
  v.literal('gif'), 
  v.literal('bmp'), 
  v.literal('svg'), 
  v.literal('webp'),
  v.literal('mpg'), 
  v.literal('mpeg'), 
  v.literal('mp2'), 
  v.literal('mpe'), 
  v.literal('mpv'), 
  v.literal('m4p'), 
  v.literal('m4v'), 
  v.literal('flv'), 
  v.literal('swf'), 
  v.literal('avchd'),
  v.literal('odt'), 
  v.literal('ods'), 
  v.literal('odp'), 
  v.literal('odg'), 
  v.literal('odf'), 
  v.literal('tex'), 
  v.literal('rtf'),
  v.literal('7z'), 
  v.literal('tar'), 
  v.literal('gz'), 
  v.literal('bz2'), 
  v.literal('s7z'), 
  v.literal('jar'), 
  v.literal('war'), 
  v.literal('xip'), 
  v.literal('iso'),
  v.literal('html'), 
  v.literal('css'), 
  v.literal('js'), 
  v.literal('ts'), 
  v.literal('java'), 
  v.literal('py'), 
  v.literal('rb'), 
  v.literal('go'), 
  v.literal('php'), 
  v.literal('cpp'), 
  v.literal('c'), 
  v.literal('cs'), 
  v.literal('swift'), 
  v.literal('kt'), 
  v.literal('rs'), 
  v.literal('lua'),
  v.literal('sql'), 
  v.literal('db'), 
  v.literal('dbf'), 
  v.literal('mdb'), 
  v.literal('accdb'),
  v.literal('ttf'), 
  v.literal('otf'), 
  v.literal('fon'), 
  v.literal('fnt')
)



export const mimeTypes: { [key: string ]: string } = {
  "image": "image/*",
  "csv": "text/csv",
  "pdf": "application/pdf",
  "doc": "application/msword",
  "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "xls": "application/vnd.ms-excel",
  "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "ppt": "application/vnd.ms-powerpoint",
  "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "txt": "text/plain",
  "zip": "application/zip",
  "rar": "application/x-rar-compressed",
  "mp4": "video/mp4",
  "mov": "video/quicktime",
  "avi": "video/x-msvideo",
  "mkv": "video/x-matroska",
  "flv": "video/x-flv",
  "wmv": "video/x-ms-wmv",
  "mp3": "audio/mpeg",
  "wav": "audio/wav",
  "flac": "audio/flac",
  "aac": "audio/aac",
  "ogg": "audio/ogg",
  "jpeg": "image/jpeg",
  "png": "image/png",
  "gif": "image/gif",
  "bmp": "image/bmp",
  "svg": "image/svg+xml",
  "webp": "image/webp",
  "mpg": "video/mpeg",
  "mpeg": "video/mpeg",
  "mp2": "audio/mpeg",
  "mpe": "video/mpeg",
  "mpv": "video/mpeg",
  "m4p": "video/mp4",
  "m4v": "video/x-m4v",
  "swf": "application/x-shockwave-flash",
  "avchd": "video/x-m2ts",
  "odt": "application/vnd.oasis.opendocument.text",
  "ods": "application/vnd.oasis.opendocument.spreadsheet",
  "odp": "application/vnd.oasis.opendocument.presentation",
  "odg": "application/vnd.oasis.opendocument.graphics",
  "odf": "application/vnd.oasis.opendocument.formula",
  "tex": "application/x-tex",
  "rtf": "application/rtf",
  "7z": "application/x-7z-compressed",
  "tar": "application/x-tar",
  "gz": "application/gzip",
  "bz2": "application/x-bzip2",
  "s7z": "application/x-7z-compressed",
  "jar": "application/java-archive",
  "war": "application/java-archive",
  "xip": "application/x-xip",
  "iso": "application/x-iso9660-image",
  "html": "text/html",
  "css": "text/css",
  "js": "application/javascript",
  "ts": "application/typescript",
  "java": "text/x-java-source",
  "py": "text/x-python",
  "rb": "application/x-ruby",
  "go": "text/x-go",
  "php": "application/x-httpd-php",
  "cpp": "text/x-c++src",
  "c": "text/x-csrc",
  "cs": "text/x-csharp",
  "swift": "text/x-swift",
  "kt": "text/x-kotlin",
  "rs": "text/rust",
  "lua": "text/x-lua",
  "sql": "application/sql",
  "db": "application/octet-stream",
  "dbf": "application/x-dbf",
  "mdb": "application/x-msaccess",
  "accdb": "application/msaccess",
  "ttf": "font/ttf",
  "otf": "font/otf",
  "fon": "application/x-font-fon",
  "fnt": "application/x-font-fnt"
}

export default defineSchema({
  files: defineTable({ 
    name: v.string(), 
    orgId: v.string(), 
    isFavorite: v.boolean(),
    inTrash: v.boolean(),
    type: fileTypes, 
    fileId: v.id("_storage") 
  })
  .index("by_orgId", ["orgId"]),
  users: defineTable({
    tokenIdentifier: v.string(),
    orgIds: v.array(v.string()),
  }).index('by_tokenIdentifier', ['tokenIdentifier']),
});